# Generated by Django 5.0.2 on 2024-03-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_customuser_profile_photo_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='name',
            field=models.CharField(default='profile_photo_<built-in function id>', max_length=40),
        ),
    ]
