# Generated by Django 5.0.2 on 2024-03-13 13:50

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profilephoto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='Media/Generic-Profile-Image.png', upload_to=authentication.models.upload_to),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='name',
            field=models.CharField(default='profile_photo_2550816298656', max_length=40),
        ),
    ]
